import { createAuth, databaseAdapter } from "@init/auth/server"
import { admin, organization } from "@init/auth/server/plugins"
import { tanstackStartCookies } from "@init/auth/start"
import { database } from "@init/db/client"
import env from "#shared/env.ts"
import { baseUrl } from "#shared/utils.ts"

export const auth = createAuth(
  databaseAdapter(database()),
  {
    secret: env.AUTH_SECRET,
    baseURL: baseUrl,
    emailAndPassword: {
      enabled: true,
      autoSignIn: true,
    },
    advanced: {
      // Rely on the IDs generated by the database
      database: { generateId: false },
    },
    socialProviders: {
      google: {
        enabled: true,
        clientId: env.GOOGLE_CLIENT_ID,
        clientSecret: env.GOOGLE_CLIENT_SECRET,
      },
      github: {
        enabled: true,
        clientId: env.GITHUB_CLIENT_ID,
        clientSecret: env.GITHUB_CLIENT_SECRET,
      },
    },
  },
  [admin(), organization(), tanstackStartCookies()]
)

export type Auth = typeof auth
export type Session = typeof auth.$Infer.Session
