import { db } from "@this/db/client"
import env from "@this/env/auth/server"
import { betterAuth } from "better-auth"
import { drizzleAdapter } from "better-auth/adapters/drizzle"
import { admin } from "better-auth/plugins"
import { hashPassword, verifyPassword } from "#password.ts"

export const auth = betterAuth({
  baseUrl: env.BETTER_AUTH_URL,
  secret: env.BETTER_AUTH_SECRET,
  database: drizzleAdapter(db, {
    provider: "sqlite",
    usePlural: true,
  }),
  emailAndPassword: {
    enabled: true,
    password: {
      hash: hashPassword,
      verify: verifyPassword,
    },
  },
  advanced: {
    // We rely on ids generated by the database
    generateId: false,
  },
  user: {
    additionalFields: {
      publicId: {
        type: "string",
        required: false,
        input: false,
        fieldName: "public_id",
      },
    },
  },
  session: {
    expiresIn: 60 * 60 * 24 * 30,
    updateAge: 60 * 60 * 24 * 15,
  },
  databaseHooks: {
    account: {
      create: {
        before: async ({ accountId, ...rest }) => ({
          data: {
            ...rest,
            // Relying on JavaScript parsing of numbers to strings rather than
            // the database's
            accountId: accountId.toString(),
          },
        }),
      },
    },
  },
  trustedOrigins: env.BETTER_AUTH_TRUSTED_ORIGINS,
  plugins: [admin()],
})

export type Auth = typeof auth
export type Session = typeof auth.$Infer.Session
