packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # React
  react: 19.0.0
  react-dom: 19.0.0
  "@types/react": 19.0.14
  "@types/react-dom": 19.0.4
  server-only: 0.0.1

  # React Native
  react-native: 0.79.2
  react-native-reanimated: 3.17.5
  nativewind: 4.1.23
  "@sentry/react-native": 6.10.0
  "@react-navigation/native": 7.1.7
  "@roninoss/icons": "0.0.4"

  # Next.js
  next: 15.3.1
  "@next/bundle-analyzer": 15.3.1

  # TanStack
  "@tanstack/react-query": 5.75.2
  "@tanstack/react-form": 1.9.0
  "@tanstack/react-router": 1.119.0
  "@tanstack/router-devtools": 1.119.1
  "@tanstack/router-plugin": 1.119.0

  # TRPC
  "@trpc/client": 11.1.2
  "@trpc/server": 11.1.2
  "@trpc/tanstack-react-query": 11.1.2

  # Styling
  class-variance-authority: 0.7.1
  lucide-react: 0.475.0

  # Development
  "@types/node": 22.15.3
  typescript: 5.8.3
  vite: 6.3.5
  vitest: 3.1.3

  # Other
  hono: 4.7.8
  pino: 9.6.0
  superjson: 2.2.2
  zod: 3.24.4

catalogs:
  tailwind3:
    tailwindcss: 3.4.17

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@sentry/cli"
  - "@upstash/qstash-cli"
  - core-js
  - core-js-pure
  - dtrace-provider
  - esbuild
  - msw
  - sharp
  - spawn-sync
  - workerd
