packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  "@hookform/resolvers": 4.1.0
  "@next/bundle-analyzer": 15.1.7
  "@sentry/react-native": 6.7.0
  "@tailwindcss/postcss": 4.0.6
  "@tanstack/react-form": 1.0.0
  "@tanstack/react-query": 5.67.2
  "@tanstack/react-router": 1.105.0
  "@tanstack/router-devtools": 1.105.0
  "@tanstack/router-plugin": 1.105.0
  "@trpc/server": "11.0.0-rc.828"
  "@types/node": 22.13.4
  "@types/react-dom": 18.3.5
  "@types/react": 18.3.18
  "@vercel/functions": 2.0.0
  autoprefixer: 10.4.20
  class-variance-authority: 0.7.1
  hono: 4.7.1
  lucide-react: 0.475.0
  nativewind: 4.1.23
  next-axiom: 1.9.1
  next: 15.1.7
  pino: 9.6.0
  postcss: 8.5.2
  react-dom: 18.3.1
  react-hook-form: 7.54.2
  react-native-reanimated: 3.16.7
  react-native: 0.77.1
  react: 18.3.1
  server-only: 0.0.1
  superjson: 2.2.2
  tailwindcss-animate: 1.0.7
  typescript: 5.7.3
  vite: 6.1.0
  vitest: 3.0.5
catalogs:
  tailwind3:
    tailwindcss: 3.4.17
  tailwind4:
    tailwindcss: 4.0.6
