packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # React
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": 18.3.18
  "@types/react-dom": 18.3.5
  server-only: 0.0.1

  # React Native
  react-native: 0.77.1
  react-native-reanimated: 3.17.1
  nativewind: 4.1.23
  "@sentry/react-native": 6.9.1

  # Next.js
  next: 15.2.2
  "@next/bundle-analyzer": 15.2.2

  # TanStack
  "@tanstack/react-query": 5.68.0
  "@tanstack/react-form": 1.0.5
  "@tanstack/react-router": 1.114.17
  "@tanstack/router-devtools": 1.114.21
  "@tanstack/router-plugin": 1.114.17

  # TRPC
  "@trpc/client": 11.0.0
  "@trpc/server": 11.0.0
  "@trpc/tanstack-react-query": 11.0.0

  # Styling
  postcss: 8.5.3
  "@tailwindcss/postcss": 4.0.14
  tailwindcss-animate: 1.0.7
  class-variance-authority: 0.7.1
  lucide-react: 0.475.0

  # Development
  "@types/node": 22.13.10
  typescript: 5.8.2
  vite: 6.2.2
  vitest: 3.0.8

  # Other
  hono: 4.7.4
  pino: 9.6.0

catalogs:
  tailwind3:
    tailwindcss: 3.4.17
  tailwind4:
    tailwindcss: 4.0.14

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@sentry/cli"
  - "@upstash/qstash-cli"
  - core-js
  - core-js-pure
  - dtrace-provider
  - esbuild
  - msw
  - sharp
  - spawn-sync
  - workerd
