import { cn } from "@this/ui/utils"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import type { ReactNode } from "react"

import "@tooling/tailwind/globals.css"

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn("font-sans", inter.variable)}>{children}</body>
    </html>
  )
}
