import { createAuth, databaseAdapter } from "@init/auth/server"
import { admin, organization } from "@init/auth/server/plugins"
import { database } from "@init/db/client"
import { APP_ID } from "@init/utils/constants"
import env from "#shared/env.ts"

export const auth = createAuth(
  databaseAdapter(database()),
  {
    advanced: {
      // Rely on the IDs generated by the database
      cookiePrefix: APP_ID,
      database: { generateId: false },
    },
    basePath: "/auth",
    baseURL: env.BASE_URL,
    emailAndPassword: {
      autoSignIn: true,
      enabled: true,
    },
    secret: env.AUTH_SECRET,
    socialProviders: {
      github: {
        clientId: env.GITHUB_CLIENT_ID,
        clientSecret: env.GITHUB_CLIENT_SECRET,
        enabled: true,
      },
      google: {
        clientId: env.GOOGLE_CLIENT_ID,
        clientSecret: env.GOOGLE_CLIENT_SECRET,
        enabled: true,
      },
    },
    trustedOrigins: env.ALLOWED_API_ORIGINS,
  },
  [admin(), organization()]
)

export type Auth = typeof auth
export type Session = Auth["$Infer"]["Session"]
