// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

// biome-ignore lint/complexity/noBannedTypes: This can be filled by adding bindings.
// biome-ignore lint/correctness/noUnusedVariables: This is a declaration file.
type CloudflareBindings = {}
