// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

// biome-ignore lint/complexity/noBannedTypes: Empty object type is generated by Wrangler
// biome-ignore lint/correctness/noUnusedVariables: Empty object type is generated by Wrangler
type CloudflareBindings = {}
